apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gateway
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-gateway
  template:
    metadata:
      labels:
        app: server-gateway
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: server-gateway
        image: agrrisk-server-gateway
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7002
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        env:
        - name: TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: TENANT_ID
        - name: APPLICATION_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: APPLICATION_CLIENT_ID
        - name: APPLICATION_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: APPLICATION_CLIENT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: server-gateway
spec:
  type: NodePort  # Cambiado a NodePort para Minikube
  ports:
  - port: 7002
    targetPort: 7002
    nodePort: 30009  # Especifica un puerto entre 30000-32767
  selector:
    app: server-gateway

# kubectl apply -f server-gateway-deployment.yaml