apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-auth
  template:
    metadata:
      labels:
        app: api-auth
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: api-auth
        image: agrrisk-api-auth
        imagePullPolicy: Never
        ports:
        - containerPort: 7100
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-auth
spec:
  type: NodePort  # Cambiado a NodePort para Minikube
  ports:
  - port: 7100
    targetPort: 7100
    nodePort: 30050  # Especifica un puerto entre 30000-32767
  selector:
    app: api-auth

# kubectl apply -f api-auth-deployment.yaml