apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-discovery
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-discovery
  template:
    metadata:
      labels:
        app: server-discovery
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: server-discovery
        image: agrrisk-server-discovery
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: server-discovery
spec:
  type: NodePort  # Cambiado a NodePort para Minikube
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 30008  # Especifica un puerto entre 30000-32767
  selector:
    app: server-discovery

# kubectl apply -f server-discovery-deployment.yaml